import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const EULA = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background p-6">
      <div className="max-w-4xl mx-auto">
        <div className="mb-6">
          <Button
            variant="ghost"
            onClick={() => navigate(-1)}
            className="mb-4"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back
          </Button>
          <h1 className="text-3xl font-bold">End User License Agreement</h1>
          <p className="text-muted-foreground">PlayNexus AI Creator by Nortaq</p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Software License Terms</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm max-w-none space-y-6">
            <p><strong>Effective Date:</strong> {new Date().toLocaleDateString()}</p>
            
            <section>
              <h3 className="text-lg font-semibold mb-2">License Grant</h3>
              <p className="text-muted-foreground">
                Nortaq grants you a non-exclusive, non-transferable license to use PlayNexus AI Creator 
                in accordance with these terms. This software is designed to help you create applications 
                and tools using AI assistance.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-semibold mb-2">Ownership of Generated Content</h3>
              <div className="text-muted-foreground space-y-2">
                <p><strong>You own all rights to:</strong></p>
                <ul className="list-disc list-inside">
                  <li>Code generated by the AI based on your prompts</li>
                  <li>Applications and projects created using this software</li>
                  <li>Any derivative works you create</li>
                  <li>Commercial use of generated content without attribution requirements</li>
                </ul>
              </div>
            </section>

            <section>
              <h3 className="text-lg font-semibold mb-2">Permitted Uses</h3>
              <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                <li>Personal and commercial development projects</li>
                <li>Educational and research purposes</li>
                <li>Creating applications for clients or employers</li>
                <li>Open source and proprietary software development</li>
                <li>Distribution of generated applications under any license</li>
              </ul>
            </section>

            <section>
              <h3 className="text-lg font-semibold mb-2">Restrictions</h3>
              <div className="text-muted-foreground">
                <p>You may not:</p>
                <ul className="list-disc list-inside">
                  <li>Redistribute, resell, or sublicense the PlayNexus AI Creator software itself</li>
                  <li>Reverse engineer, decompile, or disassemble the core application</li>
                  <li>Use the software for illegal activities or to generate malicious code</li>
                  <li>Attempt to circumvent usage limits or security measures</li>
                </ul>
              </div>
            </section>

            <section>
              <h3 className="text-lg font-semibold mb-2">AI Service Disclaimer</h3>
              <p className="text-muted-foreground">
                When using cloud AI services, generated code is provided "as-is". While we strive for 
                quality, AI-generated code should be reviewed and tested before production use. 
                Nortaq is not responsible for bugs or issues in AI-generated code.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-semibold mb-2">Privacy and Data</h3>
              <p className="text-muted-foreground">
                See our Privacy Policy for details on data handling. Your generated code and projects 
                remain your property and are not used to train AI models or shared with third parties.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-semibold mb-2">Warranty Disclaimer</h3>
              <p className="text-muted-foreground">
                This software is provided "AS IS" without warranty of any kind. Nortaq disclaims all 
                warranties, express or implied, including merchantability and fitness for a particular purpose.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-semibold mb-2">Contact & Support</h3>
              <div className="text-muted-foreground">
                <p><strong>Developer:</strong> Nortaq</p>
                <p><strong>Email:</strong> playnexushq@gmail.com</p>
                <p><strong>Support:</strong> Available via email for technical issues and licensing questions</p>
              </div>
            </section>

            <p className="text-xs text-muted-foreground pt-4 border-t">
              By using PlayNexus AI Creator, you acknowledge that you have read, understood, 
              and agree to be bound by these terms.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default EULA;